######################################################################
# Automatically generated by qmake (2.01a) Tue Aug 28 14:09:38 2012
######################################################################

TEMPLATE = app
TARGET = 
#	DEPENDPATH += .
#INCLUDEPATH += .

# RESOURCES = netmon-qt.qrc

# QMAKE_LIBS += -lboost_program_options

QMAKE_CXXFLAGS += -std=c++0x

# Input
HEADERS += netgroup.hpp netmon-qt-window.hpp
SOURCES += netmon-qt.cpp netmon-qt-window.cpp

